---
- name: download objectStoreConsumer from artifact repo
  maven_artifact: repository_url={{ artifactory_url }} group_id=gov.loc artifact_id=objectStoreConsumer version={{ install_version }} extension=zip dest=/tmp
  register: artifact

- name: install objectStoreConsumer from zip
  unarchive: copy=no dest=/opt src={{ artifact.dest }}

- name: delete tmp rpm file
  file: path={{ artifact.dest }}  state=absent

  - name: run objectStoreConsumer
  shell: /opt/objectStoreConsumer/bin/objectStore