---
- name: download objectStoreMaster from artifact repo
  maven_artifact: repository_url={{ artifactory_url }} group_id=gov.loc artifact_id=objectStoreMaster version={{ install_version }} extension=rpm dest=/tmp
  register: artifact

- name: install objectStoreMaster from rpm
  yum: name={{ artifact.dest }} state=present

- name: delete tmp rpm file
  file: path={{ artifact.dest }}  state=absent

  - name: run metadataStore
  shell: /opt/loc-rdc/objectStoreMaster/bin/objectStoreMaster